import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface":                   "#131313",
        "surface-dim":               "#131313",
        "surface-bright":            "#393939",
        "surface-container":         "#201f1f",
        "surface-container-low":     "#1c1b1b",
        "surface-container-high":    "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-container-lowest":  "#0e0e0e",
        "surface-variant":           "#353534",
        "surface-tint":              "#ffb783",
        "primary":                   "#ffb783",
        "primary-container":         "#db7619",
        "primary-fixed":             "#ffdcc5",
        "primary-fixed-dim":         "#ffb783",
        "on-primary":                "#4f2500",
        "on-primary-container":      "#451f00",
        "on-primary-fixed":          "#301400",
        "on-primary-fixed-variant":  "#713700",
        "secondary":                 "#b5c8df",
        "secondary-container":       "#36485b",
        "secondary-fixed":           "#d1e4fb",
        "secondary-fixed-dim":       "#b5c8df",
        "on-secondary":              "#203243",
        "on-secondary-container":    "#a4b7cd",
        "on-secondary-fixed":        "#091d2e",
        "on-secondary-fixed-variant":"#36485b",
        "tertiary":                  "#8adb4d",
        "tertiary-container":        "#56a315",
        "tertiary-fixed":            "#a5f866",
        "tertiary-fixed-dim":        "#8adb4d",
        "on-tertiary":               "#183800",
        "on-tertiary-container":     "#143000",
        "on-tertiary-fixed":         "#0b2000",
        "on-tertiary-fixed-variant": "#255100",
        "background":                "#131313",
        "on-background":             "#e5e2e1",
        "on-surface":                "#e5e2e1",
        "on-surface-variant":        "#e0c0b2",
        "outline":                   "#a88a7e",
        "outline-variant":           "#594238",
        "inverse-primary":           "#944a00",
        "inverse-surface":           "#e5e2e1",
        "inverse-on-surface":        "#313030",
        "error":                     "#ffb4ab",
        "error-container":           "#93000a",
        "on-error":                  "#690005",
        "on-error-container":        "#ffdad6",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body:     ["Manrope", "sans-serif"],
        label:    ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
